### PR TITLE
Avoid use of uname (replaces PR # 435)

### PR DESCRIPTION
**Pull request by dmurdoch**

### CODE REVIEW

**Comment by jonathon-love** [comment]
looks good!

**Comment by jonathon-love** [comment]
i appreciate this is a bit of a minor change, but if you had time to push this to CRAN, i know a few people who will benefit from it.

kind regards

**Comment by dmurdoch** [comment]
I'll try, but they rejected my last submission.

**Comment by dmurdoch** [comment]
It appears to have been accepted this time.  Look for 1.3.12.

**Comment by jonathon-love** [comment]
w00t!

with thanks

**Pull request merged**
